services:
  etl:
    build:
      context: ./backend
      target: prod
    command: sh -c "pnpm build && pnpm etl"
    volumes: []
    environment:
      NODE_ENV: production
  backend:
    build:
      context: ./backend
      target: prod
    command: sh -c "pnpm build && pnpm start"
    environment:
      NODE_ENV: production
      volumes: []
  frontend:
    build:
      context: ./frontend
      target: prod
    command: sh -c "pnpm build && pnpm start"
    environment:
      NODE_ENV: production
    volumes: []
