services:
  db:
    image: postgres:18
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./data/raw:/data/raw
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl: 
    build:
      context: ./backend
      target: deps
    container_name: etl_job
    restart: "no"
    depends_on:
      db: 
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: pnpm etl:dev
    env_file:
      - .env

  backend:
    build: 
      context: ./backend
      target: deps
    container_name: node_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: pnpm dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
    env_file:
      - .env

  frontend:
    build: 
      context: ./frontend
      target: deps
    container_name: next_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: pnpm dev --webpack
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
      WATCHPACK_POLLING: "true"
    env_file:
      - .env

volumes:
  postgres_data:
